services:
  db:
    image: postgres:16
    container_name: fashion_store_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fashion_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - fashion_store_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fashion_store_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fashion_store_api
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  fashion_store_postgres_data:
